name: Latest blog post workflow
on:
  workflow_dispatch:
  push:
    branches: 
      - master
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://epispot.github.io/epiblog/feed.xml"
          max_post_count: 5
